### ISSUE TITLE
[Bug] dev deploy action 실패 시 기존 컨테이너 정지됨

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/zabo-front-reactjs#169]
# Describe the bug

아래 cd pipeline에서 docker pull 명령이 실패했을 때 다음 커맨드들이 계속 실행되어 기존 컨테이너가 종료되는 문제가 발생합니다.
`script_stop: true` 옵션을 넣어 docker pull 명령이 실패했을 때 다음 커맨드들이 실행되지 않게 합니다.

```yaml
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          script: |
            docker pull ghcr.io/sparcs-kaist/zabo-front:dev
            docker rm -f zabo-front
            docker run --restart always -d -p 15081:80 --name zabo-front ghcr.io/sparcs-kaist/zabo-front:dev
```

# To Reproduce

1. docker pull에서 오류 발생 (github container registry용 token 만료 등으로)
2. 아래 명령이 계속 실행되어 zabo-front 컨테이너가 삭제됨

# Screenshots

없음.
